### ISSUE TITLE
"An error occurred on client" - Front-end issue?

### ISSUE THREAD

**Issue by dlogvin** [web3labs/chainlens-free#71]
It seems like everything is working. Blocks are getting imported:
```
2024-02-20T23:08:49.988Z  INFO 1 --- [pool-5-thread-6] i.e.e.i.blocks.BlockHeightExtractor      : Import reached block 22024 (0x48fc4fdaf22d1bc12532ce6f81b7390654aeadd4f5cc3877af913575ffebd8fa)
```
etc. etc.

The problem is that whenever I try to open the `localhost`, I am presented with a blank screen with text that says "An error occurred on client." This is affecting all pages.

In firefox, the following appears in the console:

```
TypeError: u.oW is undefined
    NextJS 8
    NextJS 21
TypeError: u.oW is undefined
    NextJS 8
```

In chrome, the following appears:
```
TypeError: Cannot read properties of undefined (reading 'concat')
    at 238-7651b095e46b62511564.js:1:20012
    at Ii (framework-7612f137f39df1be4160.js:1:105611)
    at t.unstable_runWithPriority (framework-7612f137f39df1be4160.js:1:130410)
    at Wl (framework-7612f137f39df1be4160.js:1:45782)
    at Oi (framework-7612f137f39df1be4160.js:1:105072)
    at framework-7612f137f39df1be4160.js:1:104983
    at D (framework-7612f137f39df1be4160.js:1:129469)
    at w.port1.onmessage (framework-7612f137f39df1be4160.js:1:128191)
```

**Comment by bhaskarsharma2710** [comment]
it is fixed for me

**Comment by sergioarevro** [comment]
Works for me too, thanks!

**Comment by haerker** [comment]
@mnkhod thanks! i love you!

**Comment by giovannyCaluna** [comment]
It works for me too. Thank u so much

**Comment by dlogvin** [comment]
As the issue has been fixed, I'm closing this issue.
