### ISSUE TITLE
inexact rounding

### ISSUE THREAD

**Issue by lesaux** [web3labs/chainlens-free#73]
Hello,
I tried connecting chainlens to a private geth network running POA clique v1.13.14 and seeing this weird error.
Any idea what I could look into?
This log comes from the ingestion process.

```
Caused by: java.lang.NumberFormatException: Conversion to Decimal128 would require inexact rounding of 899999999989999996999.94388034539486037
	at org.bson.types.Decimal128.ensureExactRounding(Decimal128.java:250) ~[bson-4.9.1.jar!/:na]
	at org.bson.types.Decimal128.clampAndRound(Decimal128.java:239) ~[bson-4.9.1.jar!/:na]
	at org.bson.types.Decimal128.<init>(Decimal128.java:175) ~[bson-4.9.1.jar!/:na]
	at org.bson.types.Decimal128.<init>(Decimal128.java:162) ~[bson-4.9.1.jar!/:na]
	at io.epirus.explorer.ingestion.transactions.processors.TransactionAccountsProcessor.getEntityUpdate(TransactionAccountsProcessor.kt:94) ~[classes!/:3.3.10]
	at io.epirus.explorer.ingestion.transactions.processors.TransactionAccountsProcessor.process$lambda$10(TransactionAccountsProcessor.kt:43) ~[classes!/:3.3.10]
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]"```

**Comment by Julius278** [comment]
I'm currently facing the same issue while synching a private besu blockchain..
